#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=20gb
#PBS -l walltime=0:30:00
#PBS -N app-compute-tract-stats
#PBS -V

set -e

# generate csv that can be useful in MLC analyses
[ ! -f ./tractmeasures/output_FiberStats.csv ] && SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/pyafq:dev ./quickStats.py

if [ -f ./tractmeasures/output_FiberStats.csv ]; then
	echo "complete"
	exit 0
else
	echo "stats computations failed somewhere. please check logs and derivatives"
	exit 1
fi
